name: release

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          ls -lah
          cd server && yarn
      - name: zip
        run: |
          ls -lah
          cd ..
          zip -r mongodb-prisma.zip mongodb-prisma
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: mongodb-prisma.zip
